#!/bin/bash

export CUDA_VISIBLE_DEVICES=1

for length in {10..25}
do
    python -u motif_specific_generation_improved.py \
    -sm '/home/tc415/moPPIt/moppit/model_path/finetune_bindevaluator_0/model-epoch=30-val_mcc=0.60-val_loss=0.51.ckpt' \
    -n_layers 8 \
    -d_model 128 \
    -d_hidden 128 \
    -n_head 8 \
    -d_inner 64 \
    --protein_seq 'MSEYIRVTEDENDEPIEIPSEDDGTVLLSTVTAQFPGACGLRYRNPVSQCMRGVRLVEGILHAPDAGWGNLVYVVNYPKDNKRKMDETDASSAVKVKRAVQKTSDLIVLGLPWKTTEQDLKEYFSTFGEVLMVQVKKDLKTGHSKGFGFVRFTEYETQVKVMSQRHMIDGRWCDCKLPNSKQSQDEPLRSRKVFVGRCTEDMTEDELREFFSQYGDVMDVFIPKPFRAFAFVTFADDQIAQSLCGEDLIIKGISVHISNAEPKHNSNRQLERSGRFGGNPGGFGNQGGFGNSRGGGAGLGNNQGSNMGGGMNFGAFSINPAMMAAAQAALQSSWGMMGMLASQQNQSGPSGNNQNQGNMQREPNQAFGSGNNSYSGSNSGAAIGWGSASNAGSGSGFNGGFGSSMDSKSSGWGM' \
    --peptide_length $length \
    --motif '[276-413]' \
    --top_k 3 \
    --num_binders 100 \
    --num_display 20
done